name: GitHub Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "该作业由${{github.event_name}}事件自动触发"
      - run: echo "此作业现在正在GitHub托管的${{runner.os}}服务器上运行"
      - run: echo "分支的名称是${{github.ref}}，存储库是${{github.repository}}"
      - name: 签出存储库代码
        uses: actions/checkout@v2
      - run: echo "${{github.repository}}存储库已克隆到运行程序"
      - name: 列出存储库中的文件
        run: |
          ls ${{ github.workspace }}
      - name: 列出Package发布的文件
        run: |
          ls Package
      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: V${{ env.ReleaseVersion }}
          title: Version ${{ env.ReleaseVersion }}
          prerelease: true
          files: |
            Package/*.nupkg
      - run: echo "此作业的状态为${{job.status}}"